name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: terraform/environments/lab
  TF_STATE_BUCKET: gcp-test-504808-tfstate-18325870326

concurrency:
  group: terraform-lab
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: gcp-test-504808
          workload_identity_provider: projects/18325870326/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-deployer@gcp-test-504808.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.8"

      - name: Terraform Init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="prefix=lab"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -lock-timeout=5m \
            -out=tfplan

      - name: Terraform Apply
        run: |
          terraform apply \
            -input=false \
            -lock-timeout=5m \
            tfplan